############################################
# Study browser: pick a ProfusionEEG study from a folder's study list, set the
# report options, and generate the report.
#
#   python study_browser.py [folder]
#
# The folder is one holding ProfusionEEG study subfolders and their
# "_CMPStudyList.mdb" index (see studylist.py). Reports are generated by
# spawning study_runner.py, so the analysis - which loads TensorFlow and draws
# matplotlib figures - stays off this process's Qt event loop and can be
# cancelled outright.
############################################
import os
import sys
import json

from PyQt6.QtCore import Qt, QProcess, QSettings, QUrl
from PyQt6.QtGui import QDesktopServices, QFont
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, QGridLayout,
    QFormLayout, QLabel, QLineEdit, QPushButton, QCheckBox, QComboBox,
    QDoubleSpinBox, QTableWidget, QTableWidgetItem, QHeaderView, QGroupBox,
    QPlainTextEdit, QFileDialog, QMessageBox, QSplitter, QAbstractItemView,
    QProgressBar, QSizePolicy)

import studylist
import study_runner

LANGUAGES = ['english', 'traditional chinese', 'simplified chinese', 'japanese',
             'korean', 'spanish', 'french', 'german']

LLM_MODELS = ['gemini-1.5-pro', 'gemini-1.5-flash', 'claude-3-5-sonnet-20240620',
              'gpt-4o']

COLUMNS = ['Date', 'Surname', 'Given name', 'DOB', 'Sex', 'Length', 'Rate',
           'Channels', 'Study']


def formatDuration(seconds):
    """Seconds as H:MM:SS."""
    if not seconds:
        return ''
    seconds = int(seconds)
    return '%d:%02d:%02d' % (seconds // 3600, (seconds % 3600) // 60, seconds % 60)


class SortableItem(QTableWidgetItem):
    """Table cell that sorts on a supplied key rather than its display text.

    Needed so durations shown as H:MM:SS and blank cells sort sensibly.
    """

    def __init__(self, text, sortKey=None):
        super().__init__(text)
        self.setFlags(self.flags() & ~Qt.ItemFlag.ItemIsEditable)
        self._sortKey = text if sortKey is None else sortKey

    def __lt__(self, other):
        mine, theirs = self._sortKey, getattr(other, '_sortKey', None)
        # None sorts last regardless of direction, so studies missing a field
        # do not sit above the ones that have it.
        if mine is None:
            return False
        if theirs is None:
            return True
        try:
            return mine < theirs
        except TypeError:
            return str(mine) < str(theirs)


class StudyBrowser(QMainWindow):
    def __init__(self, root=None):
        super().__init__()
        self.setWindowTitle('ProfusionEEG Study Browser')
        self.resize(1180, 820)

        self.settings = QSettings('Compumedics', 'EEG-AI-Report-StudyBrowser')
        self.studies = []
        self.process = None
        self.reportPdf = None

        self._buildUi()
        self._restoreOptions()

        root = root or self.settings.value('root', '', type=str)
        if root:
            self.rootEdit.setText(root)
            self.loadStudies()

    # ---------------------------------------------------------------- layout

    def _buildUi(self):
        central = QWidget()
        self.setCentralWidget(central)
        outer = QVBoxLayout(central)

        # --- study folder -------------------------------------------------
        folderRow = QHBoxLayout()
        folderRow.addWidget(QLabel('Study folder:'))
        self.rootEdit = QLineEdit()
        self.rootEdit.setPlaceholderText(
            'Folder containing ProfusionEEG studies and %s'
            % studylist.STUDY_LIST_FILENAME)
        self.rootEdit.returnPressed.connect(self.loadStudies)
        folderRow.addWidget(self.rootEdit, 1)
        browse = QPushButton('Browse...')
        browse.clicked.connect(self.browseRoot)
        folderRow.addWidget(browse)
        reload_ = QPushButton('Reload')
        reload_.clicked.connect(self.loadStudies)
        folderRow.addWidget(reload_)
        outer.addLayout(folderRow)

        self.sourceLabel = QLabel()
        self.sourceLabel.setWordWrap(True)
        self.sourceLabel.setStyleSheet('color: #888;')
        outer.addWidget(self.sourceLabel)

        splitter = QSplitter(Qt.Orientation.Vertical)
        outer.addWidget(splitter, 1)

        # --- study table --------------------------------------------------
        self.table = QTableWidget(0, len(COLUMNS))
        self.table.setHorizontalHeaderLabels(COLUMNS)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.table.setSortingEnabled(True)
        self.table.verticalHeader().setVisible(False)
        self.table.itemSelectionChanged.connect(self._selectionChanged)
        self.table.doubleClicked.connect(self.generate)
        header = self.table.horizontalHeader()
        header.setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)
        header.setSectionResizeMode(COLUMNS.index('Study'),
                                    QHeaderView.ResizeMode.Stretch)
        splitter.addWidget(self._wrap('Studies', self.table))

        # --- options ------------------------------------------------------
        splitter.addWidget(self._buildOptions())

        # --- actions ------------------------------------------------------
        actions = QHBoxLayout()
        self.generateButton = QPushButton('Generate report')
        self.generateButton.setDefault(True)
        self.generateButton.clicked.connect(self.generate)
        self.generateButton.setEnabled(False)
        actions.addWidget(self.generateButton)

        self.cancelButton = QPushButton('Cancel')
        self.cancelButton.clicked.connect(self.cancel)
        self.cancelButton.setEnabled(False)
        actions.addWidget(self.cancelButton)

        self.openButton = QPushButton('Open report')
        self.openButton.clicked.connect(self.openReport)
        self.openButton.setEnabled(False)
        actions.addWidget(self.openButton)

        self.progress = QProgressBar()
        self.progress.setRange(0, 1)
        self.progress.setValue(0)
        self.progress.setTextVisible(False)
        actions.addWidget(self.progress, 1)
        outer.addLayout(actions)

        # --- log ----------------------------------------------------------
        self.log = QPlainTextEdit()
        self.log.setReadOnly(True)
        self.log.setMaximumBlockCount(5000)
        self.log.setFont(QFont('Consolas', 9))
        splitter.addWidget(self._wrap('Log', self.log))
        splitter.setSizes([320, 260, 240])

    def _wrap(self, title, widget):
        box = QGroupBox(title)
        layout = QVBoxLayout(box)
        layout.addWidget(widget)
        return box

    def _buildOptions(self):
        box = QGroupBox('Report options')
        grid = QGridLayout(box)

        # -- output --------------------------------------------------------
        outputForm = QFormLayout()
        outRow = QHBoxLayout()
        self.outEdit = QLineEdit('./reports')
        outRow.addWidget(self.outEdit, 1)
        outBrowse = QPushButton('...')
        outBrowse.setFixedWidth(30)
        outBrowse.clicked.connect(self.browseOut)
        outRow.addWidget(outBrowse)
        outputForm.addRow('Output folder', outRow)

        self.pdfCheck = QCheckBox('Write PDF report')
        self.pdfCheck.setChecked(True)
        outputForm.addRow('', self.pdfCheck)

        self.aiCheck = QCheckBox('Add LLM-written report')
        self.aiCheck.toggled.connect(self._aiToggled)
        outputForm.addRow('', self.aiCheck)

        self.langCombo = QComboBox()
        self.langCombo.setEditable(True)
        self.langCombo.addItems(LANGUAGES)
        outputForm.addRow('Report language', self.langCombo)

        self.modelCombo = QComboBox()
        self.modelCombo.setEditable(True)
        self.modelCombo.addItems(LLM_MODELS)
        self.modelCombo.currentTextChanged.connect(lambda _: self._aiToggled())
        outputForm.addRow('LLM model', self.modelCombo)

        self.apiLabel = QLabel()
        self.apiLabel.setWordWrap(True)
        outputForm.addRow('', self.apiLabel)
        grid.addLayout(outputForm, 0, 0)

        # -- signal selection ----------------------------------------------
        signalForm = QFormLayout()
        self.segmentCombo = QComboBox()
        self.segmentCombo.addItems(['longest', 'concat'])
        self.segmentCombo.setToolTip(
            'A study may contain gaps where data packets were lost, and a read '
            'must never cross one.\n'
            'longest: analyse the single biggest gap-free block.\n'
            'concat: join every recorded block end-to-end - more signal, but a '
            'discontinuity at each join.')
        signalForm.addRow('Data segments', self.segmentCombo)

        self.maxSecondsEdit = QLineEdit()
        self.maxSecondsEdit.setPlaceholderText('blank = all recorded signal')
        self.maxSecondsEdit.setToolTip(
            'Cap on how much signal to load, in seconds. Useful for overnight '
            'studies.')
        signalForm.addRow('Load at most (s)', self.maxSecondsEdit)

        self.tminEdit = QLineEdit()
        self.tminEdit.setPlaceholderText('blank = from the start')
        signalForm.addRow('Analyse from (s)', self.tminEdit)

        self.tmaxEdit = QLineEdit()
        self.tmaxEdit.setPlaceholderText('blank = to the end')
        signalForm.addRow('Analyse to (s)', self.tmaxEdit)

        self.autoEyeCheck = QCheckBox('Infer eye state from the signal')
        self.autoEyeCheck.setToolTip(
            'SCORE scores the reactivity of the posterior dominant rhythm to eye '
            'opening, which needs to know when the eyes were open.\n\n'
            'Off (default): reactivity is scored only where the recording carries '
            'eye-state annotations, and reported as "not possible to determine" '
            'otherwise.\n\n'
            'On: eyes-open and eyes-closed periods are inferred from posterior '
            'alpha power and frontal blink activity. This makes reactivity '
            'scorable on unmarked recordings, but on a continuously eyes-closed '
            'recording it has split the record and reported a reduced reactivity '
            'that was not there - which would drive the whole PDR to abnormal. '
            'Treat any reactivity finding it produces as unconfirmed.')
        self.autoEyeCheck.toggled.connect(self._autoEyeToggled)
        signalForm.addRow('', self.autoEyeCheck)

        self.autoEyeWarning = QLabel()
        self.autoEyeWarning.setWordWrap(True)
        signalForm.addRow('', self.autoEyeWarning)
        grid.addLayout(signalForm, 0, 1)

        # -- artifact handling ---------------------------------------------
        artifactForm = QFormLayout()
        self.repairCheck = QCheckBox('Detect and repair artifacts')
        self.repairCheck.setChecked(True)
        self.repairCheck.setToolTip(
            'Off: no artifact repair, and no bad-channel detection.')
        artifactForm.addRow('', self.repairCheck)

        self.dropSdSpin = QDoubleSpinBox()
        self.dropSdSpin.setRange(0.5, 10.0)
        self.dropSdSpin.setSingleStep(0.1)
        self.dropSdSpin.setDecimals(2)
        self.dropSdSpin.setValue(2.2)
        self.dropSdSpin.setToolTip(
            'Epochs beyond this many standard deviations of amplitude are '
            'dropped. Lower is stricter.')
        artifactForm.addRow('Drop epochs beyond (SD)', self.dropSdSpin)

        self.badRatioSpin = QDoubleSpinBox()
        self.badRatioSpin.setRange(0.0, 1.0)
        self.badRatioSpin.setSingleStep(0.05)
        self.badRatioSpin.setDecimals(2)
        self.badRatioSpin.setValue(0.3)
        self.badRatioSpin.setToolTip(
            'A channel repaired in more than this fraction of epochs is '
            'reported as a bad electrode.')
        artifactForm.addRow('Bad electrode above (ratio)', self.badRatioSpin)

        self.renameCheck = QCheckBox('Map channel names to 10-20')
        self.renameCheck.setChecked(True)
        self.renameCheck.setToolTip(
            'Normalises names such as "EEG Fp1-REF" to "Fp1". Turn off only if '
            'a montage is already in plain 10-20 names and renaming misfires.')
        artifactForm.addRow('', self.renameCheck)
        grid.addLayout(artifactForm, 0, 2)

        box.setSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        self._aiToggled()
        self._autoEyeToggled()
        return box

    def _autoEyeToggled(self):
        """Say plainly what turning the inference on costs."""
        if self.autoEyeCheck.isChecked():
            self.autoEyeWarning.setText(
                'Reactivity findings are unconfirmed - verify before signing.')
            self.autoEyeWarning.setStyleSheet('color: #8c5a0f;')
        else:
            self.autoEyeWarning.setText(
                'Reactivity scored only from eye-state annotations.')
            self.autoEyeWarning.setStyleSheet('color: #888;')

    # ------------------------------------------------------------- studies

    def browseRoot(self):
        start = self.rootEdit.text() or os.getcwd()
        folder = QFileDialog.getExistingDirectory(self, 'Select study folder', start)
        if folder:
            self.rootEdit.setText(folder)
            self.loadStudies()

    def browseOut(self):
        start = self.outEdit.text() or os.getcwd()
        folder = QFileDialog.getExistingDirectory(self, 'Select output folder', start)
        if folder:
            self.outEdit.setText(folder)

    def loadStudies(self):
        root = self.rootEdit.text().strip().strip('"')
        self.table.setRowCount(0)
        self.studies = []
        self.generateButton.setEnabled(False)

        if not root:
            self.sourceLabel.setText('')
            return
        if not os.path.isdir(root):
            self.sourceLabel.setText('Not a folder: %s' % root)
            return

        try:
            studies, source, note = studylist.loadStudies(root)
        except Exception as e:
            self.sourceLabel.setText('Could not list studies: %s' % e)
            return

        self.studies = studies
        self.settings.setValue('root', root)

        if source == 'mdb':
            message = 'Read %d study/studies from %s' % (
                len(studies), studylist.STUDY_LIST_FILENAME)
        else:
            message = '%d study/studies. %s' % (len(studies), note or '')
        self.sourceLabel.setText(message)

        self._fillTable()

    def _fillTable(self):
        # Sorting must be off while filling, or rows move under the writes.
        self.table.setSortingEnabled(False)
        self.table.setRowCount(len(self.studies))

        for row, study in enumerate(self.studies):
            date = study.get('StudyDate')
            dob = study.get('DateOfBirth')
            length = study.get('StudyLength')
            missing = study.get('missing_channels')

            if missing is None:
                channels = 'unknown'
            elif missing:
                channels = 'missing ' + ', '.join(missing)
            else:
                channels = 'OK'

            cells = [
                SortableItem(date.strftime('%Y-%m-%d %H:%M') if date else '', date),
                SortableItem(study.get('Surname') or ''),
                SortableItem(study.get('GivenName') or ''),
                SortableItem(dob.strftime('%Y-%m-%d') if dob else '', dob),
                SortableItem(study.get('Gender') or ''),
                SortableItem(formatDuration(length), length),
                SortableItem('%g Hz' % study['sfreq'] if study.get('sfreq') else '',
                             study.get('sfreq')),
                SortableItem(channels, channels),
                SortableItem(study.get('StudyPath') or study['path']),
            ]
            if not study.get('exists'):
                cells[-1].setText((cells[-1].text() or '') + '  (folder missing)')
            for column, cell in enumerate(cells):
                # The row index is the link back to self.studies, and survives
                # re-sorting because it rides on the item.
                cell.setData(Qt.ItemDataRole.UserRole, row)
                self.table.setItem(row, column, cell)

        self.table.setSortingEnabled(True)
        # Set the order explicitly: re-enabling sorting otherwise applies
        # whatever sort indicator the header happens to be carrying.
        self.table.sortItems(COLUMNS.index('Date'), Qt.SortOrder.AscendingOrder)

    def selectedStudy(self):
        rows = self.table.selectionModel().selectedRows() if self.table.selectionModel() else []
        if not rows:
            return None
        index = self.table.item(rows[0].row(), 0).data(Qt.ItemDataRole.UserRole)
        return self.studies[index]

    def _selectionChanged(self):
        study = self.selectedStudy()
        self.generateButton.setEnabled(
            bool(study) and study.get('exists', False) and self.process is None)

    # ------------------------------------------------------------- options

    def _aiToggled(self):
        """Show whether the selected model has a usable key in config.env."""
        enabled = self.aiCheck.isChecked()
        self.langCombo.setEnabled(enabled)
        self.modelCombo.setEnabled(enabled)
        if not enabled:
            self.apiLabel.setText('')
            return
        _, error = study_runner.resolveApiKey(self.modelCombo.currentText())
        if error:
            self.apiLabel.setText(error)
            self.apiLabel.setStyleSheet('color: #b00;')
        else:
            self.apiLabel.setText('API key found in config.env')
            self.apiLabel.setStyleSheet('color: #070;')

    def _optionalFloat(self, edit, label):
        """Parse an optional numeric field. Raises ValueError with a UI-ready message."""
        text = edit.text().strip()
        if not text:
            return None
        try:
            return float(text)
        except ValueError:
            raise ValueError('%s must be a number (or blank), got %r' % (label, text))

    def collectOptions(self, study):
        # The study list holds date of birth as a real date, so prefer it over
        # the study's own numeric one whose day/month order is unmarked.
        dob = study.get('DateOfBirth')
        return {
            'study': study['path'],
            'patientDob': dob.strftime('%Y-%m-%d') if dob is not None else None,
            'dest_pdfPath': self.outEdit.text().strip() or './reports',
            'outputPdf': self.pdfCheck.isChecked(),
            'aiReport': self.aiCheck.isChecked(),
            'reportLang': self.langCombo.currentText().strip() or 'english',
            'llm_model': self.modelCombo.currentText().strip(),
            'profusionSegment': self.segmentCombo.currentText(),
            'profusionMaxSeconds': self._optionalFloat(self.maxSecondsEdit,
                                                       'Load at most'),
            'tmin': self._optionalFloat(self.tminEdit, 'Analyse from'),
            'tmax': self._optionalFloat(self.tmaxEdit, 'Analyse to'),
            'autoEyeState': self.autoEyeCheck.isChecked(),
            'useRepair': self.repairCheck.isChecked(),
            'dropEpochSD': self.dropSdSpin.value(),
            'removeEpochsRationThreshold': self.badRatioSpin.value(),
            'renameChannels': self.renameCheck.isChecked(),
        }

    def _saveOptions(self):
        for key, value in [('out', self.outEdit.text()),
                           ('pdf', self.pdfCheck.isChecked()),
                           ('ai', self.aiCheck.isChecked()),
                           ('lang', self.langCombo.currentText()),
                           ('model', self.modelCombo.currentText()),
                           ('segment', self.segmentCombo.currentText()),
                           ('maxSeconds', self.maxSecondsEdit.text()),
                           ('autoEye', self.autoEyeCheck.isChecked()),
                           ('tmin', self.tminEdit.text()),
                           ('tmax', self.tmaxEdit.text()),
                           ('repair', self.repairCheck.isChecked()),
                           ('dropSd', self.dropSdSpin.value()),
                           ('badRatio', self.badRatioSpin.value()),
                           ('rename', self.renameCheck.isChecked())]:
            self.settings.setValue('opt/' + key, value)

    def _restoreOptions(self):
        s = self.settings
        self.outEdit.setText(s.value('opt/out', './reports', type=str))
        self.pdfCheck.setChecked(s.value('opt/pdf', True, type=bool))
        self.aiCheck.setChecked(s.value('opt/ai', False, type=bool))
        self.langCombo.setCurrentText(s.value('opt/lang', 'english', type=str))
        self.modelCombo.setCurrentText(s.value('opt/model', LLM_MODELS[1], type=str))
        self.segmentCombo.setCurrentText(s.value('opt/segment', 'longest', type=str))
        self.maxSecondsEdit.setText(s.value('opt/maxSeconds', '', type=str))
        self.autoEyeCheck.setChecked(s.value('opt/autoEye', False, type=bool))
        self.tminEdit.setText(s.value('opt/tmin', '', type=str))
        self.tmaxEdit.setText(s.value('opt/tmax', '', type=str))
        self.repairCheck.setChecked(s.value('opt/repair', True, type=bool))
        self.dropSdSpin.setValue(s.value('opt/dropSd', 2.2, type=float))
        self.badRatioSpin.setValue(s.value('opt/badRatio', 0.3, type=float))
        self.renameCheck.setChecked(s.value('opt/rename', True, type=bool))
        self._aiToggled()

    # --------------------------------------------------------------- running

    def generate(self):
        if self.process is not None:
            return
        study = self.selectedStudy()
        if not study or not study.get('exists'):
            return

        missing = study.get('missing_channels')
        if missing:
            answer = QMessageBox.warning(
                self, 'Channels missing',
                'This study\'s montage is missing %s.\n\nThe analysis needs all '
                '19 channels of the 10-20 montage and will stop early. Run '
                'anyway?' % ', '.join(missing),
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No)
            if answer != QMessageBox.StandardButton.Yes:
                return

        try:
            options = self.collectOptions(study)
        except ValueError as e:
            QMessageBox.warning(self, 'Check the options', str(e))
            return

        try:
            os.makedirs(options['dest_pdfPath'], exist_ok=True)
            # Written beside the report so the exact run can be repeated with
            # "python study_runner.py <this file>".
            optionsPath = os.path.join(
                options['dest_pdfPath'],
                os.path.basename(study['path']).split('.')[0] + '_options.json')
            with open(optionsPath, 'w', encoding='utf-8') as f:
                json.dump(options, f, indent=2)
        except OSError as e:
            QMessageBox.warning(self, 'Cannot write to output folder', str(e))
            return

        self._saveOptions()
        self.log.clear()
        self.reportPdf = None
        self.openButton.setEnabled(False)
        self._setRunning(True)
        self._append('Running %s\n' % os.path.basename(study['path']))

        self.process = QProcess(self)
        # One merged stream keeps the interleaving of prints and warnings
        # readable, which matters because the pipeline logs to both.
        self.process.setProcessChannelMode(QProcess.ProcessChannelMode.MergedChannels)
        self.process.setWorkingDirectory(os.path.dirname(os.path.abspath(__file__)))
        self.process.readyReadStandardOutput.connect(self._readProcess)
        self.process.finished.connect(self._processFinished)
        self.process.errorOccurred.connect(self._processError)
        # -u so output arrives line by line rather than in blocks at exit.
        self.process.start(sys.executable,
                           ['-u', 'study_runner.py', os.path.abspath(optionsPath)])

    def cancel(self):
        if self.process is None:
            return
        self._append('\n-- cancelled --\n')
        self.process.kill()

    def _readProcess(self):
        data = bytes(self.process.readAllStandardOutput())
        text = data.decode('utf-8', errors='replace')
        for line in text.splitlines():
            if line.startswith('REPORT_PDF: '):
                self.reportPdf = line[len('REPORT_PDF: '):].strip()
            self._append(line + '\n')

    def _append(self, text):
        self.log.moveCursor(self.log.textCursor().MoveOperation.End)
        self.log.insertPlainText(text)
        self.log.moveCursor(self.log.textCursor().MoveOperation.End)

    def _processError(self, error):
        self._append('\nCould not run study_runner.py: %s\n' % error.name)

    def _processFinished(self, exitCode, _status):
        self.process = None
        self._setRunning(False)
        if self.reportPdf and os.path.isfile(self.reportPdf):
            self.openButton.setEnabled(True)
            self._append('\nDone. Report: %s\n' % self.reportPdf)
        elif exitCode == 0:
            self._append('\nFinished (no PDF requested).\n')
        else:
            self._append('\nFailed (exit code %d). See the log above.\n' % exitCode)
        self._selectionChanged()

    def _setRunning(self, running):
        self.generateButton.setEnabled(not running)
        self.cancelButton.setEnabled(running)
        self.table.setEnabled(not running)
        # An indeterminate bar: the pipeline reports no overall progress.
        self.progress.setRange(0, 0 if running else 1)
        self.progress.setValue(0)

    def openReport(self):
        if self.reportPdf:
            QDesktopServices.openUrl(QUrl.fromLocalFile(self.reportPdf))

    def closeEvent(self, event):
        if self.process is not None:
            self.process.kill()
            self.process.waitForFinished(3000)
        self._saveOptions()
        super().closeEvent(event)


def main():
    app = QApplication(sys.argv)
    root = sys.argv[1] if len(sys.argv) > 1 else None
    window = StudyBrowser(root)
    window.show()
    return app.exec()


if __name__ == '__main__':
    sys.exit(main())
